# Generated by Django 5.0.7 on 2024-08-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeCongreso',
            fields=[
                ('idcongreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('asistenciatotal', models.IntegerField()),
                ('estado', models.CharField(default='ACTIVO', max_length=11)),
            ],
            options={
                'db_table': 'mae_congreso',
                'managed': False,
            },
        ),
    ]
