# Generated by Django 5.0.7 on 2024-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeParticipantes',
            fields=[
                ('codparticipante', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'mae_participantes',
                'managed': False,
            },
        ),
    ]
