# Generated by Django 5.0.7 on 2024-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeUniversidad',
            fields=[
                ('iduniversidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('ruc', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'mae_universidad',
                'managed': False,
            },
        ),
    ]
