# Generated by Django 5.0.7 on 2024-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeBloque',
            fields=[
                ('idbloque', models.AutoField(primary_key=True, serialize=False)),
                ('horainicio', models.TimeField(verbose_name='Desde')),
                ('horafin', models.TimeField(verbose_name='Hasta')),
                ('direccion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'mae_bloque',
                'managed': False,
            },
        ),
    ]
