# Generated by Django 5.0.7 on 2024-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueColaborador',
            fields=[
                ('idbc', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bloque_colaborador',
                'managed': False,
            },
        ),
    ]
