# Generated by Django 5.0.7 on 2024-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeColaborador',
            fields=[
                ('idcolaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'mae_colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaeTipousuario',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('dstipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mae_tipousuario',
                'managed': False,
            },
        ),
    ]
