# Generated by Django 5.0.7 on 2024-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeCongresoJinis',
            fields=[
                ('idcongreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
            options={
                'db_table': 'mae_congreso_jinis',
                'managed': False,
            },
        ),
    ]
