# Generated by Django 5.0.7 on 2024-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeTipoParticipante',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('dstipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mae_tipo_participante',
                'managed': False,
            },
        ),
    ]
