# Generated by Django 5.0.7 on 2024-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaeTipoUsuario',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('dstipo', models.CharField(max_length=20)),
                ('estado', models.CharField(default='ACTIVO', max_length=11)),
            ],
            options={
                'db_table': 'mae_tipousuario',
                'managed': False,
            },
        ),
    ]
